version: '3'
services:

  guitar:
    depends_on:
      - db
    image: felipe3b/api-java-guitar:latest
    restart: always
    container_name: guitar
    networks:
      - guitar
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    container_name: db-01
    environment:
      - MYSQL_DATABASE=db_guitar
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=apppasswd
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - TZ=America/Sao_Paulo
    networks:
      - guitar
    ports:
      - "3306:3306"

networks:
  guitar:
    name: guitar
    driver: bridge
