## Example Alertmangar config  alertmanager.yml file https://github.com/prometheus/alertmanager/blob/main/doc/examples/simple.yml
## DOC https://prometheus.io/docs/alerting/latest/configuration/

global:
 
route:
  receiver: GmailNotifications
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
 
receivers:
  - name: GmailNotifications
    email_configs:
      - to: felipe3b@gmail.com
        from: alert-prometheus@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: felipe3b@gmail.com
        auth_identity: felipe3b@gmail.com
        auth_password: 'kqyx muob dica ocpz'
        send_resolved: true
        headers:
          subject: 'Prometheus Mail Alerts'